### ISSUE TITLE
Hey Guys I've been having a hell of a lot of trouble with the installation

### ISSUE THREAD

**Issue by webmasteradmin** [wealthbot-io/wealthbot#103]
Can someone upload a virtual box image somewhere that I can just explore just to see wealthbot in its full glory ?

Even the demo doesn't  seem to be working !

**Comment by kjethwani** [comment]
I'd the same experience. Finally got the AWS image installed. While the installation worked fine apparently, yet unable to login as superadmin or register new client. Wonder if the project is still supported.

**Comment by vlad-ko** [comment]
the project is currently on hold. we're in the process of rebuilding the architecture, which will be released early next year.

if you are interested in helping or providing team support please reach out to me.

thanks for your patience.

**Comment by KevinColemanInc** [comment]
@vlad-ko any updates on the next release?

**Comment by webmasteradmin** [comment]
@vlad-ko I'm really interested to see if Wealthbot can see the day of light. Please do let me know if there's anything I can help with !

**Comment by janajri** [comment]
@vlad-ko I may also be very interested in contributing to the project. Would also be interested in understanding if this would be able to manage real estate portfolios.

**Comment by vlad-ko** [comment]
@webmasteradmin @janajri hi guys, i really appreciate your interest in the project. unfortunately, due to the lack of availability, i am not able to commit to the project to build out the necessary features. any community efforts to keep it going would be great, but it's been very hard to find developers/designers and other contributors. i am more than happy to provide some assistance to pass on the knowledge as long as someone can step up to support the project in the mean time.

**Comment by pandiyanmkm** [comment]
hi all. 

can anyone please give a proper guidelines to install a wealthbot in localhost windows (developement) and godaddy (production) server.

i have trying to install  using this guidelines ,

https://wealthbot.readme.io/docs/getting-started

but not able to install properly in my local.

kindly advice me

**Comment by KevinColemanInc** [comment]
@pandiyanmkm 

This project is no longer supported unfortunately.  So you are probably going to be on your own.  IMHO, you should avoid using it if there aren't any maintainers.

https://github.com/wealthbot-io/wealthbot#please-note-this-project-is-not-actively-supported-we-are-keeping-this-code-up-because-its-free-and-open-enjoy-at-your-own-risk

**Comment by pandiyanmkm** [comment]
@KevinColemanInc 

Thanks for your reply. if you found any update on welthbot installation. kindly keep posting us.

**Comment by azatyan** [comment]
Try again guys.

**Comment by lancehaynie** [comment]
I know this is super old, but I did put together a quick run through on how to install on a basic machine with Apache & PHP. I am very tempted to start migrating this project to PHP 7 and Symfony 3.4.

I have done this a few times just to make sure it works every time. It is a bit of a challenge to install with such legacy requirements.

https://confluence.haynienetworks.com/x/CIAn

**Comment by vlad-ko** [comment]
@lancehaynie ... Fantastic job. I am super busy with work, so I cannot support the project, but I can give you contributor access. 

I get a few requests for the development and would be happy to send you a referral.

**Comment by lancehaynie** [comment]
I can try my best, I have never used Symfony and Twig so I have a bit of a learning curve ahead of me. I am not sure if it is best to work out the bugs and then upgrade the system to Symfony 3 or 4 and PHP 7; or try upgrading now. I attempted to get the system at least on Symfony 3 as well as update some out of date/no longer maintained dependencies. But there are apparently some major differences between Symfony 2 and 3. Also a bit of a struggle to kind of reverse engineer some of the "why it was done xyz way." For instance, the current Mongo dependency has been depreciated. However, I am still unsure why some things are done in MySQL and some are done in MongoDB.
