### ISSUE TITLE
Get stuck at "Application Screen" stage

### ISSUE THREAD

**Issue by eefelix** [wealthbot-io/wealthbot#112]
Hi,

I'm trying to run the demo by step through the client "John Cage" from "Suggested Portfolio" to "Completed All Applications" stage. However, I get stuck at "Application Screen" stage.

From the client view, it seems that everything has been done:
![capture3](https://user-images.githubusercontent.com/6930218/43773228-a128fc2e-9a77-11e8-9aa1-d7fd1aa9d934.PNG)

The from the RIA view, I can see from the client list that "John Cage" is now at "Application Screen" stage:
![capture4](https://user-images.githubusercontent.com/6930218/43773300-e05906a0-9a77-11e8-8bb8-a4c01ea45246.PNG)

However, when I click the client's name, it will only show the same "Suggested Portfolio" screen, so nothing I can do to proceed to "Application Screen":
![capture5](https://user-images.githubusercontent.com/6930218/43773395-2e7a127a-9a78-11e8-9119-ac2741d91808.PNG)

Any suggestion? Thanks.

**Comment by azatyan** [comment]
We can help. Please write to tigran@createit.am

On 7 Aug 2018 3:29 pm, "eefelix" <notifications@github.com> wrote:

Hi,

I'm trying to run the demo by step through the client "John Cage" from
"Suggested Portfolio" to "Completed All Applications" stage. However, I get
stuck at "Application Screen" stage.

From the client view, it seems that everything has been done:
[image: capture3]
<https://user-images.githubusercontent.com/6930218/43773228-a128fc2e-9a77-11e8-9aa1-d7fd1aa9d934.PNG>

The from the RIA view, I can see from the client list that "John Cage" is
now at "Application Screen" stage:
[image: capture4]
<https://user-images.githubusercontent.com/6930218/43773300-e05906a0-9a77-11e8-8bb8-a4c01ea45246.PNG>

However, when I click the client's name, it will only show the same
"Suggested Portfolio" screen, so nothing I can do to proceed to
"Application Screen":
[image: capture5]
<https://user-images.githubusercontent.com/6930218/43773395-2e7a127a-9a78-11e8-9119-ac2741d91808.PNG>

Any suggestion? Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/wealthbot-io/wealthbot/issues/112>, or mute the thread

**Comment by azatyan** [comment]
I can install demo for you.
500 usd

**Comment by eefelix** [comment]
I do it again by registering a new account (Felix Lee in below screenshot), and finally I could get pass the whole application process.

![capture1](https://user-images.githubusercontent.com/6930218/44011058-dabea89c-9ee8-11e8-9558-18f4e4a0afc8.PNG)

Some extra stuffs need to be setup properly in order to get it done, like smtp server, docusign account, and the symfony bundles.
