### ISSUE TITLE
Register as client 

### ISSUE THREAD

**Issue by dunnston** [wealthbot-io/wealthbot#43]
On my local machine I get an error when I click register as client. I got this error after the initial instal before making any changes in the application. 

Here is there error: 

ERROR - Symfony\Component\HttpKernel\Exception\NotFoundHttpException: Ria user does not exist. (uncaught exception) at /srv/wealthbot/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php line 142

**Comment by vlad-ko** [comment]
Hi, the problem is in this file (on that line):
https://github.com/wealthbot-io/wealthbot/blob/75ec1e08168072cee0e012501bdf0a177588b98a/src/Wealthbot/UserBundle/Resources/views/Default/index.html.twig#L26

as sad as it is the ID is hard-coded "39" .. this demo landing page is "fake". a real installation would not have as the main page of the app. so we didn't put much thought into it.

if you have loaded fixtures you may login as a super admin find mortal kombat advisors and replace the id with the one in your system. this will give you a valid client registration link for the ID, which refers to mortal kombat advisors on your local.

HTH

**Comment by dunnston** [comment]
Makes perfect sense. Thank you for clearing this up so quickly!

**Comment by vlad-ko** [comment]
np. i'll keep this open because making it dynamic isn't all that hard (i just need to stop being lazy)... :)

**Comment by dunnston** [comment]
You won't get any agreement from me. I do the same thing constantly with my project. I wouldn't call it lazy as much as I would call it good time management. Time is a limited resource so it makes sense to spend the little bit of time you have focusing on areas that will have a bigger impact. 

You might consider adding something about this to the documentation though, so others don't run into the same problem. With that said, there is a good chance it is extremely obvious to others, but just went over my head due to lack of paying attention or experience.
